# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel
sudo: false
cache: packages
before_install:
  - wget -O blast.rpm ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.6.0/ncbi-blast-2.6.0+-1.x86_64.rpm
  - sudo apt-get install alien
  - sudo alien -i blast.rpm
  - rm blast.rpm
  #install diamond
  - wget https://github.com/bbuchfink/diamond/releases/download/v0.9.30/diamond-linux64.tar.gz -O /tmp/diamond.tar.gz
  - mkdir -p diamond
  - tar -xvzf /tmp/diamond.tar.gz -C diamond
  - sudo cp $PWD/diamond/* /usr/bin
after_success:
  - Rscript -e 'covr::codecov()'
