# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r: bioc-devel
sudo: false
cache: packages
before_install:
  - wget -O blast.rpm ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.6.0/ncbi-blast-2.6.0+-1.x86_64.rpm
  - sudo apt-get install alien
  - sudo alien -i blast.rpm
  - rm blast.rpm
after_success:
  - Rscript -e 'covr::codecov()'
